# Main menu, displayed in navbar
menu:
  home: /
  archives: /archives
  about: /about

logo: lchord's notes

# baidu-site-verification
baidu_site_verification:
  enable: true
  content: tQKoWHXsWW

# Google Analytics
## Tracking ID
ga_id: UA-128661785-1
## gtag.js
gtag:
  enable: true

# comment
## Disqus
disqus:
  enable: true
  shortname: lchord