home: Home
archives: Archives
about: About

category: Category
tag: Tag

posted_on: Posted on
sorted_in: In

prev: Prev
next: Next

post:
  nav-prev: Prev
  nav-next: Next

archive:
  posts:
    zero: No posts...
    one: 1 post...
    other: Totally %d posts now...